# ===================================
#  Relation Behavior Config
# ===================================

opens:

    label: mandr.mail::lang.models.email.tab_opens
    readOnly: true
    view:
        list: $/mandr/mail/models/emailopens/columns.yaml
        defaultSort:
            column: created_at
            direction: desc
    manage:
        form: $/mandr/mail/models/emailopens/fields.yaml
