# ===================================
#  Form Behavior Config
# ===================================

name: mandr.mail::lang.controllers.mail.title
form: $/mandr/mail/models/email/fields.yaml
modelClass: Mandr\Mail\Models\Email
defaultRedirect: mandr/mail/mail

preview:
    title: mandr.mail::lang.controllers.mail.preview
