# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    views:
        label: mandr.mail::lang.models.email.code
        conditions: code in (:filtered)

    bounced:
        label: mandr.mail::lang.models.email.show_bounced
        type: checkbox
        conditions: sent = 0
