# ===================================
#  List Behavior Config
# ===================================

title: mandr.mail::lang.controllers.template.title
list: $/mandr/mail/models/template/columns.yaml
modelClass: System\Models\MailTemplate
recordUrl: mandr/mail/template/stats/:id

recordsPerPage: 20
noRecordsMessage: backend::lang.list.no_records
showSetup: true

defaultSort:
    column: id
    direction: desc

toolbar:
    search:
        prompt: backend::lang.list.search_prompt
